apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: frontend
          image: 172.26.0.1:8081/docker-local/frontend
      imagePullSecrets:
        - name: artifactorysecret5
